### ISSUE TITLE
Add more secondary constructors for JSON matchers

### ISSUE THREAD

**Issue by g4s8** [g4s8/matchers-json#13]
Add constructors for most used scenarios, to simplify the code:
 - [x] `JsonHas(String, String)` (same as `JsonHas(String, JsonValueIs(String))` #14
 - [x] `JsonHas(String, Number)` (same as `JsonHas(String, JsonValueIs(Number))` #14
 - [x] `JsonHas(String, boolean)` (same as `JsonHas(String, JsonValueIs(boolean))` #14
 - [x] `JsonContains(String...)` for string arrays
 - [x] `JsonContains(Number...)` for number arrays
 - [x] `JsonContains(boolean...)` for bool arrays
